http:
  port: "8081"
  
sfdc:
  client_id: "6d9e329147164bf08a2cc4eeb075252e"
  client_secret: "B20a21B05dBb4287a7C49076D6E0d377"
  
database:
  host: "diy-accounts-api.us-w2.cloudhub.io"
  port: "80"
  protocol: "HTTP"
  basepath: "/"
  
trans:
  wsdl: http://apdev-accounts-ws.cloudhub.io/api/transactions?wsdl
  service: "TransactionServiceService"
  port: "TransactionServicePort"
  address: "http://apdev-accounts-ws.cloudhub.io/api/transactions"