http:
  port: "8081"

drinksapi:
  host: "www.thecocktaildb.com"
  basepath: "/api/json/v1/1"
foodapi:
  host: "www.themealdb.com"
  basepath: "/api/json/v1/1"
telegram:
  uri: "https://api.telegram.org"     
  token: "![Y73kXhcZQjyF83xbr+bexRseiAxS03H5Eu3gzDb4qGl5AAkRjePAoTgHOmNHLcfv]" 
  
validation:
    checkRecipe: " Hi , you forgot write cocktail name"
    checkQueryIngredient: "Please write some ingredient"
    ifTrueSizeOfVars: " Wait a little beat, we check if size valid "
    checkQueryCategory: "Please write some cocktail category"
    day: "Please write the day you are interested in"  
    payloadDailyMenu: "Sorry, something went wrong, try again please"   
   