http:
  port: "8081"
  
sfdc:
  username: "username"
  password: "password"
  token:    "token"  
  
file:
  accountsDir: "d:/AnypointStudio/APDevFundamentals4.4_studentFiles_SP_06may2022/APDevFundamentals4.4_studentFiles_SP_06may2022/resources"
db:
  host: "mudb.learn.mulesoft.com"
  port: "3306"
  user: "mule"
  password: "mule"
  database: "training"