#%RAML 1.0 NamedExample
value:
-
  idDrink: "11566"
  name: "Jewel Of The Nile"
  DrinkAlternate: null
  Tags: null
  Video: null
  Category: "Ordinary Drink"
  IBA": null
  Alcoholic: "Alcoholic"
  Glass: "Cocktail glass"
  Instructions: "In a mixing glass half-filled with ice cubes, combine all of the ingredients. Stir well. Strain into a cocktail glass."
  Recipe:
      "Gin": "1 1/2 oz "
      "Green Chartreuse": "1/2 oz "
      "Yellow Chartreuse": "1/2 oz "
      "null": null
  ImageSource: null
  ImageAttribution": null
  CreativeCommonsConfirmed": "No"