http:
  port: "8081"
  
ballapi:
  host: "www.balldontlie.io"
  basepath: "/api/v1"

database:
  URL: "jdbc:postgresql://localhost:5432/demo"
  driver: "org.postgresql.Driver"
  user: "![vLHxaHIIKgvunWo2QVaADw==]" 
  password: "![2t9+l5SdtYs=]"