#%RAML 1.0 NamedExample
value:
  -
    home_team: Milwaukee Bucks
    visitor_team: Golden State Warriors
    score: 121-124
    winner: GSW
  -
    home_team: Philadelphia 76ers
    visitor_team: Golden State Warriors
    score: 108-119
    winner: GSW
