#%RAML 1.0 NamedExample

value:
  -
    conference: East
    teams: 
      -
        team_name: Boston Celtics
        wins: 56
        losses: 34
        percentage: 0.62
      -
        team_name: Toronto Raptors
        wins: 56
        losses: 34
        percentage: 0.62
  -
    conference: west
    teams: 
      -
        team_name: Boston Celtics
        wins: 56
        losses: 34
        percentage: 0.62
      -
        team_name: Toronto Raptors
        wins: 56
        losses: 34
        percentage: 0.62